---
- name: Ensure freshrss compose directory exists
  ansible.builtin.file:
    path: "{{ freshrss_compose_dir }}"
    state: directory
    mode: "0755"

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ freshrss_compose_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  vars:
    network: "{{ traefik_network_name }}"
    compose_file_reference: "{{ freshrss_compose_dir }}/docker-compose.yml"
    image: "{{ freshrss_image }}"
    bind_dir_config: "{{ freshrss_compose_bind_dir_config }}"

- name: Start freshrss container
  community.docker.docker_compose_v2:
    project_src: "{{ freshrss_compose_dir }}"

- name: Prepare update cronjob
  ansible.builtin.template:
    src: freshrss-update.sh.j2
    dest: /usr/local/bin/freshrss-update.sh
    mode: "0750"

- name: Ensure freshrss update cronjob is set
  ansible.builtin.cron:
    name: "freshrss update"
    weekday: "*"
    minute: "0"
    hour: "2"
    job: "/usr/local/bin/freshrss-update.sh > /tmp/freshrss-update.log 2>&1"
    user: root
    cron_file: freshrss-update
