oauth2_proxy_compose_dir: /opt/docker-compose/oauth2-proxy
oauth2_proxy_image: quay.io/oauth2-proxy/oauth2-proxy:latest
oauth2_proxy_client_id: ""
oauth2_proxy_client_secret: ""
oauth2_proxy_cookie_secret: ""
oauth2_proxy_oidc_issuer_url: https://hutter-cloud.eu.auth0.com/
oauth2_proxy_cookie_domain: .hutter.cloud
